// Package docs is auto-generated by swag.
// Run: swag init -g cmd/server/main.go -o ./docs
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CRM Backend API",
	Description:      "Professional CRM API — Client & Interesting Client Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "CRM Backend API",
    "description": "Professional CRM API — Client & Interesting Client Management",
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Type 'Bearer' followed by a space and your JWT token."
    }
  },
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "Register a new user",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/RegisterRequest"}}],
        "responses": {"201":{"description":"Created"}}
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login and receive JWT token",
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/LoginRequest"}}],
        "responses": {"200":{"description":"OK"}}
      }
    },
    "/auth/me": {
      "get": {
        "tags": ["Auth"],
        "summary": "Get current user profile",
        "security": [{"BearerAuth":[]}],
        "responses": {"200":{"description":"OK"}}
      }
    },
    "/auth/profile": {
      "put": {
        "tags": ["Auth"],
        "summary": "Update current user profile",
        "security": [{"BearerAuth":[]}],
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/UpdateProfileRequest"}}],
        "responses": {"200":{"description":"OK"}}
      }
    },
    "/auth/change-password": {
      "post": {
        "tags": ["Auth"],
        "summary": "Change password",
        "security": [{"BearerAuth":[]}],
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/ChangePasswordRequest"}}],
        "responses": {"200":{"description":"OK"}}
      }
    },
    "/levels": {
      "get":  {"tags":["Levels"],"summary":"List all levels","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"OK"}}},
      "post": {"tags":["Levels"],"summary":"Create a level","security":[{"BearerAuth":[]}],"parameters":[{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/LevelRequest"}}],"responses":{"201":{"description":"Created"}}}
    },
    "/levels/{id}": {
      "put":    {"tags":["Levels"],"summary":"Update level","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}},
      "delete": {"tags":["Levels"],"summary":"Delete level","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}}
    },
    "/contact-sources": {
      "get":  {"tags":["Contact Sources"],"summary":"List all contact sources","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"OK"}}},
      "post": {"tags":["Contact Sources"],"summary":"Create contact source","security":[{"BearerAuth":[]}],"parameters":[{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/ContactSourceRequest"}}],"responses":{"201":{"description":"Created"}}}
    },
    "/contact-sources/{id}": {
      "put":    {"tags":["Contact Sources"],"summary":"Update contact source","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}},
      "delete": {"tags":["Contact Sources"],"summary":"Delete contact source","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}}
    },
    "/clients": {
      "get": {
        "tags": ["Clients"],
        "summary": "List clients",
        "security": [{"BearerAuth":[]}],
        "parameters": [
          {"in":"query","name":"search","type":"string"},
          {"in":"query","name":"status","type":"string","enum":["lead","prospect","active","inactive","churned"]},
          {"in":"query","name":"type","type":"string","enum":["company","individual"]},
          {"in":"query","name":"country","type":"string"},
          {"in":"query","name":"level_id","type":"integer"},
          {"in":"query","name":"contact_source_id","type":"integer"},
          {"in":"query","name":"assigned_to_id","type":"integer"},
          {"in":"query","name":"page","type":"integer"},
          {"in":"query","name":"page_size","type":"integer"},
          {"in":"query","name":"sort_by","type":"string"},
          {"in":"query","name":"sort_dir","type":"string","enum":["asc","desc"]}
        ],
        "responses": {"200":{"description":"OK"}}
      },
      "post": {
        "tags": ["Clients"],
        "summary": "Create a client",
        "security": [{"BearerAuth":[]}],
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/CreateClientRequest"}}],
        "responses": {"201":{"description":"Created"}}
      }
    },
    "/clients/{id}": {
      "get":    {"tags":["Clients"],"summary":"Get client by ID","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}},
      "put":    {"tags":["Clients"],"summary":"Update client","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"},{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/UpdateClientRequest"}}],"responses":{"200":{"description":"OK"}}},
      "delete": {"tags":["Clients"],"summary":"Delete client (admin/manager)","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}}
    },
    "/clients/{id}/logo": {
      "post": {
        "tags":["Clients"],
        "summary":"Upload client logo",
        "security":[{"BearerAuth":[]}],
        "consumes":["multipart/form-data"],
        "parameters":[
          {"in":"path","name":"id","required":true,"type":"integer"},
          {"in":"formData","name":"file","required":true,"type":"file"}
        ],
        "responses":{"200":{"description":"OK"}}
      }
    },
    "/interesting-clients": {
      "get": {
        "tags": ["Interesting Clients"],
        "summary": "List interesting clients",
        "security": [{"BearerAuth":[]}],
        "parameters": [
          {"in":"query","name":"search","type":"string"},
          {"in":"query","name":"priority","type":"string","enum":["low","medium","high","critical"]},
          {"in":"query","name":"min_score","type":"integer"},
          {"in":"query","name":"is_converted","type":"boolean"},
          {"in":"query","name":"contact_source_id","type":"integer"},
          {"in":"query","name":"assigned_to_id","type":"integer"},
          {"in":"query","name":"page","type":"integer"},
          {"in":"query","name":"page_size","type":"integer"},
          {"in":"query","name":"sort_by","type":"string"},
          {"in":"query","name":"sort_dir","type":"string","enum":["asc","desc"]}
        ],
        "responses": {"200":{"description":"OK"}}
      },
      "post": {
        "tags": ["Interesting Clients"],
        "summary": "Create interesting client",
        "security": [{"BearerAuth":[]}],
        "parameters": [{"in":"body","name":"body","required":true,"schema":{"$ref":"#/definitions/CreateInterestingRequest"}}],
        "responses": {"201":{"description":"Created"}}
      }
    },
    "/interesting-clients/{id}": {
      "get":    {"tags":["Interesting Clients"],"summary":"Get by ID","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}},
      "put":    {"tags":["Interesting Clients"],"summary":"Update","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"},{"in":"body","name":"body","schema":{"$ref":"#/definitions/UpdateInterestingRequest"}}],"responses":{"200":{"description":"OK"}}},
      "delete": {"tags":["Interesting Clients"],"summary":"Delete (admin/manager)","security":[{"BearerAuth":[]}],"parameters":[{"in":"path","name":"id","required":true,"type":"integer"}],"responses":{"200":{"description":"OK"}}}
    },
    "/interesting-clients/{id}/convert": {
      "post": {
        "tags":["Interesting Clients"],
        "summary":"Convert to a real client",
        "security":[{"BearerAuth":[]}],
        "parameters":[
          {"in":"path","name":"id","required":true,"type":"integer"},
          {"in":"body","name":"body","schema":{"$ref":"#/definitions/ConvertRequest"}}
        ],
        "responses":{"200":{"description":"OK"}}
      }
    }
  },
  "definitions": {
    "RegisterRequest": {
      "type":"object","required":["name","email","password"],
      "properties":{"name":{"type":"string"},"email":{"type":"string","format":"email"},"password":{"type":"string","minLength":6},"role":{"type":"string","enum":["admin","manager","sales"]}}
    },
    "LoginRequest": {
      "type":"object","required":["email","password"],
      "properties":{"email":{"type":"string","format":"email"},"password":{"type":"string"}}
    },
    "ChangePasswordRequest": {
      "type":"object","required":["old_password","new_password"],
      "properties":{"old_password":{"type":"string"},"new_password":{"type":"string","minLength":6}}
    },
    "UpdateProfileRequest": {
      "type":"object",
      "properties":{"name":{"type":"string"}}
    },
    "LevelRequest": {
      "type":"object","required":["name"],
      "properties":{"name":{"type":"string"},"description":{"type":"string"},"color":{"type":"string"},"sort_order":{"type":"integer"}}
    },
    "ContactSourceRequest": {
      "type":"object","required":["name"],
      "properties":{"name":{"type":"string"},"description":{"type":"string"},"icon":{"type":"string"}}
    },
    "PhoneInput": {
      "type":"object","required":["phone"],
      "properties":{"phone":{"type":"string"},"label":{"type":"string"},"is_primary":{"type":"boolean"}}
    },
    "CreateClientRequest": {
      "type":"object","required":["name","type"],
      "properties":{
        "name":{"type":"string"},"type":{"type":"string","enum":["company","individual"]},
        "status":{"type":"string","enum":["lead","prospect","active","inactive","churned"]},
        "industry":{"type":"string"},"website":{"type":"string"},"email":{"type":"string"},
        "description":{"type":"string"},"notes":{"type":"string"},
        "annual_revenue":{"type":"number"},"currency":{"type":"string"},
        "address":{"type":"string"},"city":{"type":"string"},"province":{"type":"string"},
        "country":{"type":"string"},"post_code":{"type":"string"},
        "level_id":{"type":"integer"},"contact_source_id":{"type":"integer"},"assigned_to_id":{"type":"integer"},
        "phones":{"type":"array","items":{"$ref":"#/definitions/PhoneInput"}}
      }
    },
    "UpdateClientRequest": {
      "type":"object",
      "properties":{
        "name":{"type":"string"},"type":{"type":"string"},"status":{"type":"string"},
        "industry":{"type":"string"},"website":{"type":"string"},"email":{"type":"string"},
        "description":{"type":"string"},"notes":{"type":"string"},
        "annual_revenue":{"type":"number"},"currency":{"type":"string"},
        "address":{"type":"string"},"city":{"type":"string"},"province":{"type":"string"},
        "country":{"type":"string"},"post_code":{"type":"string"},
        "level_id":{"type":"integer"},"contact_source_id":{"type":"integer"},"assigned_to_id":{"type":"integer"},
        "phones":{"type":"array","items":{"$ref":"#/definitions/PhoneInput"}}
      }
    },
    "CreateInterestingRequest": {
      "type":"object","required":["full_name","priority"],
      "properties":{
        "full_name":{"type":"string"},"company_name":{"type":"string"},
        "email":{"type":"string"},"position":{"type":"string"},
        "address":{"type":"string"},"city":{"type":"string"},"country":{"type":"string"},
        "notes":{"type":"string"},
        "priority":{"type":"string","enum":["low","medium","high","critical"]},
        "interest_score":{"type":"integer","minimum":0,"maximum":100},
        "opportunity_value":{"type":"number"},"currency":{"type":"string"},
        "reason":{"type":"string"},"next_follow_up_at":{"type":"string","format":"date-time"},
        "contact_source_id":{"type":"integer"},"assigned_to_id":{"type":"integer"},
        "phones":{"type":"array","items":{"$ref":"#/definitions/PhoneInput"}}
      }
    },
    "UpdateInterestingRequest": {
      "type":"object",
      "properties":{
        "full_name":{"type":"string"},"company_name":{"type":"string"},
        "priority":{"type":"string","enum":["low","medium","high","critical"]},
        "interest_score":{"type":"integer"},"opportunity_value":{"type":"number"},
        "reason":{"type":"string"},"next_follow_up_at":{"type":"string","format":"date-time"},
        "phones":{"type":"array","items":{"$ref":"#/definitions/PhoneInput"}}
      }
    },
    "ConvertRequest": {
      "type":"object",
      "properties":{"existing_client_id":{"type":"integer","description":"Link to existing client instead of creating new one"}}
    }
  }
}`
